name: Analyze code and build android

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'

      - run: flutter doctor -v
      - run: |
         chmod +x ./scripts/.code_analyze.sh
         ./scripts/.code_analyze.sh
        shell: bash
      - run: flutter test --coverage
      - run: flutter build apk
      
